lib/bipbip/version.rb
=> Bump bipbip

docu/services.md, lib/bipbip/plugin/mongodb.rb, lib/bipbip/version.rb, spec/bipbip/plugin/mongodb_spec.rb
Closes #92
Paired with @kris-lab
=> Mongodb: add slow query count

lib/bipbip/plugin/mongodb.rb, lib/bipbip/version.rb
=> Add slow_queries_count to schema

lib/bipbip/plugin/mongodb.rb, lib/bipbip/version.rb, spec/bipbip/plugin/mongodb_spec.rb
=> Fix mongodb slow_queries metric name

README.md, docu/services.md, lib/bipbip/plugin/socket_redis.rb, lib/bipbip/version.rb, spec/bipbip/plugin/socket_redis_spec.rb
- Number of channels
- Number of subscribers
=> Add service plugin: socket-redis

lib/bipbip/plugin/log_parser.rb, lib/bipbip/version.rb
@kris-lab @tomaszdurka please review
Addressing https://github.com/cargomedia/bipbip/issues/105
See also https://github.com/nex3/rb-inotify/pull/43
=> Run GC to make sure inotify file descriptor is freed

lib/bipbip/plugin/log_parser.rb, lib/bipbip/version.rb
Addressing #105
@kris-lab @tomaszdurka please review
=> Expect EBADF when selecting from inotify's IO

lib/bipbip/plugin/log_parser.rb, lib/bipbip/version.rb
Addressing #105
@kris-lab @tomaszdurka please review
When the FD is invalid/closed, then closing the notifier will fail too. We should still continue the clean up then..
=> Expect closing of notifier to fail

.travis.yml, lib/bipbip/agent.rb
=> Make sure plugins die immediately on interrupt

README.md, bipbip.gemspec, lib/bipbip/agent.rb, lib/bipbip/plugin.rb, lib/bipbip/storage.rb, lib/bipbip/storage/copperegg.rb, spec/bipbip/agent_config_spec.rb, spec/bipbip/plugin_spec.rb, spec/testdata/sample_base.yml, spec/testdata/sample_base_includes.d/redis.yml
=> Introduce "tags" to attach to copperegg custom objects

lib/bipbip/version.rb
=> Bump version to 0.5.24

bin/bipbip, bipbip.gemspec, lib/bipbip.rb, lib/bipbip/agent.rb, lib/bipbip/config.rb, lib/bipbip/plugin.rb, lib/bipbip/version.rb, spec/bipbip/agent_spec.rb, spec/bipbip/config_spec.rb, spec/bipbip/plugin_spec.rb
=> Use threads instead of forking

lib/bipbip/plugin.rb, lib/bipbip/version.rb
@tomaszdurka please have a look
self-merging
=> Fix wrong time passed to measurement

lib/bipbip/plugin.rb
=> Simplify plugin factory

lib/bipbip/plugin/log_parser.rb, spec/bipbip/agent_spec.rb, spec/bipbip/plugin/log_parser_spec.rb
Extracted from #119
@kris-lab @ppp0 please review
=> Some spec improvements

lib/bipbip/plugin/mongodb.rb, lib/bipbip/version.rb
Via https://github.com/cargomedia/puppet-cargomedia/issues/820
```sh
$ sudo lsof -p $(pgrep -f 'bipbip') | grep mongodb | wc -l
675
```
=> Mongodb plugin leaks file handles

lib/bipbip/plugin/memcached.rb, lib/bipbip/version.rb, spec/bipbip/plugin/memcached_spec.rb
To determine if there's enough memory.
```
stats
[...]
STAT evictions 6262
[...]
```
@ppp0 wdyt?
=> memcached: Add "evictions"

bipbip.gemspec, lib/bipbip/plugin/monit.rb, lib/bipbip/plugin/nginx.rb, lib/bipbip/version.rb, spec/bipbip/plugin/monit_spec.rb, spec/bipbip/plugin/nginx_spec.rb
See https://www.datadoghq.com/blog/how-to-monitor-nginx/
=> Extend nginx plugin metrics?

lib/bipbip/plugin/resque.rb, lib/bipbip/version.rb, spec/bipbip/plugin/resque_spec.rb
=> Resque Failures Tracking

docu/services.md, lib/bipbip/agent.rb, lib/bipbip/plugin.rb, lib/bipbip/plugin/apache2.rb, lib/bipbip/plugin/command.rb, lib/bipbip/plugin/fastcgi_php_apc.rb, lib/bipbip/plugin/fastcgi_php_fpm.rb, lib/bipbip/plugin/fastcgi_php_opcache.rb, lib/bipbip/plugin/janus_audioroom.rb, lib/bipbip/plugin/janus_rtpbroadcast.rb, lib/bipbip/plugin/log_parser.rb, lib/bipbip/plugin/mongodb.rb, lib/bipbip/plugin/network.rb, lib/bipbip/plugin/nginx.rb, lib/bipbip/plugin/php_apc.rb, lib/bipbip/plugin/socket_redis.rb, lib/bipbip/storage.rb, lib/bipbip/storage/copperegg.rb, lib/bipbip/version.rb, spec/bipbip/agent_spec.rb
Part of https://github.com/cargomedia/puppet-packages/pull/1160
Part of https://github.com/cargomedia/puppet-cargomedia/pull/1072
=> Mongodb: add authentication

Vagrantfile, bipbip.gemspec, lib/bipbip/plugin/gearman.rb, lib/bipbip/version.rb
@fauvel @kris-lab please review
=> Add "jobs_active_total" metric for gearman

docu/services.md, lib/bipbip/plugin/puppet.rb
=> Make puppet's "lastrunfile" path configurable

.rubocop_todo.yml, lib/bipbip/plugin/janus_rtpbroadcast.rb, lib/bipbip/plugin/mongodb.rb, lib/bipbip/version.rb, spec/bipbip/plugin/janus_rtpbroadcast_spec.rb, spec/bipbip/plugin/mongodb_spec.rb
Depends on https://github.com/cargomedia/janus-gateway-rtpbroadcast/issues/95
=> Expose janus/rtp plugin packet-loss count as gauge

.rubocop_todo.yml, lib/bipbip/plugin/mongodb.rb, lib/bipbip/version.rb, spec/bipbip/plugin/mongodb_spec.rb
=> Add indices size to the mongo plugin

README.md
=> Add some docu about "development"

lib/bipbip/plugin/coturn.rb, lib/bipbip/version.rb
Part of https://github.com/cargomedia/puppet-cargomedia/issues/1482
=> coturn: improve telnet connection workflow

lib/bipbip/plugin/gearman.rb, lib/bipbip/version.rb
waiting = queued - active
(because queued includes active/running ones)
=> Gearman: add "waiting" metric

docu/services.md, lib/bipbip/plugin/gearman.rb, lib/bipbip/version.rb, spec/bipbip/plugin/gearman_spec.rb
Part of https://github.com/cargomedia/bipbip/issues/168
=> gearman: extend waiting/queued metrics with priority

docu/services.md, lib/bipbip/plugin/gearman.rb, lib/bipbip/version.rb
It is required by puppet-packages configuration like e.g. https://github.com/cargomedia/puppet-packages/pull/1564
=> Fix gearman plugin docu and introduce mysql_table param
